[platformio]
; 默认构建环境（可通过 PlatformIO 工具栏切换）
default_envs = esp32-c3, esp32-c6, esp32dev

; 跨环境共享的全局配置
[env]
framework = espidf
; 💡 强行在这里补全底层缺失的判定变量，这样三个环境都能一步到位修复
board_build.frameworks = espidf
monitor_speed = 115200
lib_ldf_mode = deep
build_flags =
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO

; --- ESP32 经典经典系列 ---
[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
board_upload.flash_size = 4MB

; --- ESP32-C3 系列（RISC-V 架构） ---
[env:esp32-c3]
platform = espressif32@6.7.0
board = esp32-c3-devkitm-1  ; 💡 修正：在 esp32 后面加上了连字符 "-"
board_build.flash_mode = dio

[env:esp32-c6]
platform = espressif32@6.7.0
board = esp32-c6-devkitc-1
board_build.flash_mode = dio
board_upload.flash_size = 2MB
; 💡 引入刚才创建的脚本
;extra_scripts = post:disable_sha256.py
