[platformio]
; 默认编译环境 (在状态栏切换时生效)
default_envs = esp32dev, esp32-c3

; 公共配置 (两个环境共享)
[env]
framework = espidf
monitor_speed = 115200

# 增加这一行，让依赖查找器强制寻找头文件
lib_ldf_mode = deep
# 引入官方组件库支持
build_flags =
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
    -D CONFIG_BOOTLOADER_LOG_LEVEL_NONE
    -D CONFIG_LOG_DEFAULT_LEVEL_NONE
    -D CONFIG_BT_ENABLED=n
# 添加以下配置，编译时禁用调试日志
    -D CONFIG_BOOTLOADER_LOG_LEVEL_NONE
    -D CONFIG_LOG_DEFAULT_LEVEL_NONE

; --- ESP32 经典款配置 ---
[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
board_upload.flash_size = 2MB

; 如果需要自定义分区表，取消下面注释
; board_build.partitions = custom_partitions.csv

; --- ESP32-C3 配置 ---
[env:esp32-c3]
platform = espressif32@6.9.0
board = esp32c3-devkitm-1
; C3 特有设置：确保使用正确的 Flash 模式
board_build.flash_mode = dio
